# Generated by Django 5.1.3 on 2025-02-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('household_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=255)),
                ('square_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('floor_count', models.IntegerField()),
                ('people_count', models.IntegerField(default=0)),
                ('dogs_count', models.IntegerField(default=0)),
                ('cats_count', models.IntegerField(default=0)),
            ],
        ),
    ]
