# Generated by Django 5.1.3 on 2024-12-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='cats_count',
        ),
        migrations.RemoveField(
            model_name='household',
            name='country',
        ),
        migrations.RemoveField(
            model_name='household',
            name='dogs_count',
        ),
        migrations.RemoveField(
            model_name='household',
            name='floor_count',
        ),
        migrations.RemoveField(
            model_name='household',
            name='people_count',
        ),
        migrations.RemoveField(
            model_name='household',
            name='square_meter',
        ),
        migrations.RemoveField(
            model_name='household',
            name='zip_code',
        ),
    ]
